### ISSUE TITLE
Hibernate Tarefas

### ISSUE THREAD

**Issue by LSantos06** [LSantos06/JavaWeb-fj21#8]
fj21-tarefas-hibernate

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/message' /Message
	at org.jboss.logging.Log4jLogger.<init>(Log4jLogger.java:31)
	at org.jboss.logging.Log4jLoggerProvider.getLogger(Log4jLoggerProvider.java:29)
	at org.jboss.logging.LoggerProviders.find(LoggerProviders.java:33)
	at org.jboss.logging.LoggerProviders.<clinit>(LoggerProviders.java:28)
	at org.jboss.logging.Logger.getLogger(Logger.java:2163)
	at org.jboss.logging.Logger.getLogger(Logger.java:2188)
	at org.hibernate.jpa.HibernatePersistenceProvider.<clinit>(HibernatePersistenceProvider.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader$CachingPersistenceProviderResolver.getPersistenceProviders(PersistenceProviderResolverHolder.java:177)
	at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader.getPersistenceProviders(PersistenceProviderResolverHolder.java:84)
	at javax.persistence.Persistence.getProviders(Persistence.java:67)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:53)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)
	at br.com.caelum.tarefas.jpa.GeraTabelas.main(GeraTabelas.java:10)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.message.Message
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

**Comment by LSantos06** [comment]
Conflito de bibliotecas
